apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: cleanup-task
spec:
  steps:
    - name: cleanup
      image: alpine
      script: |
        echo "Cleaning up workspace"

---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: run-simple-interest-task
spec:
  steps:
    - name: run-script
      image: alpine
      script: |
        chmod +x simple-interest.sh
        ./simple-interest.sh 1000 5 2
